const reincarnationTable = [
    "Aasimar",
    "Aasimar; Agathion-Blooded",
    "Aasimar; Angel-Blooded",
    "Aasimar; Archon-Blooded",
    "Aasimar; Azata-Blooded",
    "Aasimar; Garuda-Blooded",
    "Aasimar; Peri-Blooded",
    "Adaro",
    "Aphorite",
    "Aquatic Elf",
    "Astomoi",
    "Beast-kin; Cat-kin",
    "Beast-kin; Cattle-kin",
    "Beast-kin; Dog-kin",
    "Beast-kin; Lizard-kin",
    "Beast-kin; Rabbit-kin",
    "Beast-kin; Scoundrel-kin",
    "Bugbear",
    "Caligni",
    "Caligni; Dark Caller",
    "Caligni; Dark Champion",
    "Caligni; Dark Creeper",
    "Caligni; Dark Stalker",
    "Catfolk",
    "Cecaelia",
    "Changeling",
    "Changeling; Annis-Born",
    "Changeling; Ash-Born",
    "Changeling; Blood-Born",
    "Changeling; Dreamthief-Born",
    "Changeling; Green-Born",
    "Changeling; Mute-Born",
    "Changeling; Night-Born",
    "Changeling; Sea-Born",
    "Changeling; Storm-Born",
    "Changeling; Winter-Born",
    "Deep One Hybrid",
    "Dhampir",
    "Dhampir; Jiang-Shi-Born",
    "Dhampir; Moroi-Born",
    "Dhampir; Nosferatu-Born",
    "Dhampir; Vetala-Born",
    "Dragon-kin",
    "Drow",
    "Duergar",
    "Duskwalker",
    "Dwarf",
    "Elf",
    "Fetchling",
    "Ganzi",
    "Gathlain",
    "Ghoran",
    "Gillman",
    "Gnoll",
    "Gnome",
    "Goblin",
    "Grindylow",
    "Grippli",
    "Half-Elf",
    "Halfling",
    "Half-Orc",
    "Human",
    "Hobgoblin",
    "Ifrit",
    "Ifrit; Lavasoul",
    "Ifrit; Sunsoul",
    "Kasatha",
    "Kitsune",
    "Kobold",
    "Kuru",
    "Lashunta",
    "Lizardfolk; Savannah-Kin",
    "Lizardfolk; Jungle-kin",
    "Lizardfolk; Swamp-kin",
    "Locathah",
    "Merfolk",
    "Monkey Goblin",
    "Nagaji",
    "Naiad",
    "Orang-Pendak",
    "Orc",
    "Oread",
    "Oread; Gemsoul",
    "Oread; Ironsoul",
    "Ratfolk",
    "Reptoid",
    "Rougarou",
    "Sahuagin",
    "Samsaran",
    "Skinwalker",
    "Skinwalker; Wereape-Kin",
    "Skinwalker; Werebat-Kin",
    "Skinwalker; Werebear-Kin",
    "Skinwalker; Wereboar-Kin",
    "Skinwalker; Werecrocodile-Kin",
    "Skinwalker; Weremantis-Kin",
    "Skinwalker; Wereraptor-Kin",
    "Skinwalker; Wererat-Kin",
    "Skinwalker; Werescorpion-Kin",
    "Skinwalker; Wereshark-Kin",
    "Skinwalker; Werespider-Kin",
    "Skinwalker; Weretiger-Kin",
    "Skinwalker; Weretortoise-Kin",
    "Skinwalker; Werewasp-Kin",
    "Skinwalker; Werewolf-Kin",
    "Strix",
    "Suli",
    "Svirfneblin",
    "Sylph",
    "Sylph; Smokesoul",
    "Sylph; Stormsoul",
    "Syrinx",
    "Tengu",
    "Tiefling",
    "Tiefling; Asura-Spawn",
    "Tiefling; Daemon-Spawn",
    "Tiefling; Demodand-Spawn",
    "Tiefling; Demon-Spawn",
    "Tiefling; Devil-Spawn",
    "Tiefling; Div-Spawn",
    "Tiefling; Kyton-Spawn",
    "Tiefling; Oni-Spawn",
    "Tiefling; Qlippoth-Spawn",
    "Tiefling; Rakshasa-Spawn",
    "Triton",
    "Troglodyte",
    "Undead; Ghast",
    "Undead; Skeleton",
    "Undead; Zombie",
    "Undine",
    "Undine; Mistsoul",
    "Undine; Rimesoul",
    "Vanara",
    "Vine Leshy",
    "Vishkanya",
    "Wayang",
    "Wyvaran",
    "Game Masters Choice"
]

export default {
    reincarnationTable
}